import * as uport from "uport-connect";

// This would be done in a separate uPort managed app, the public address of which would be registered
// in the Bee Faucet contract. This allows us to verify the attestations generated by that app.
export const generateUniquenessAttestation = (address) => {

    uport.attestCredentials({
        sub: address,
        claim: {
            "Uniqueness": "Is Unique / Hash of their passport number"
        },
        exp: new Date().getTime() + 365 * 24 * 60 * 60 * 1000, // 1 whole year! Length requires thought.
    })

}